### ISSUE TITLE
rust build error 、コンパイルでエラーが出ます、どうしたらいいでしょう?

### ISSUE THREAD

**Issue by PeterTakahashi** [genya0407/reing#1]
error[E0599]: no method named `to_tokens` found for type `syntax::ptr::P<syntax::ast::Item>` in the current scope
   --> /Users/takahashi/.cargo/registry/src/github.com-1ecc6299db9ec823/pear_codegen-0.0.20/src/lib.rs:507:38
    |
507 |         StmtKind::Item(item) => item.to_tokens(ecx)
    |                                      ^^^^^^^^^

error: aborting due to 27 previous errors

Some errors occurred: E0432, E0433, E0557, E0599.
For more information about an error, try `rustc --explain E0432`.
error: Could not compile `pear_codegen`.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by genya0407** [comment]
@seiyatakahashi Issueを見逃してました．申し訳ないです．

このアプリケーションはnightlyコンパイラでのみコンパイルすることができます．
~私の環境ではコンパイラのバージョンは `rustc 1.32.0 (9fda7c223 2019-01-16)` です．~
私の環境ではコンパイラのバージョンは `rustc 1.32.0-nightly (f1e2fa8f0 2018-11-20)`です．
これより新しいnightlyビルドのコンパイラであれば，コンパイルが通ると思います．

@seiyatakahashi さんのrustcのバージョンはいくつですか？

**Comment by PeterTakahashi** [comment]
返信ありがとうございます。既にデプロイしている、サイトはありますか?
これから起業して行こうと思っていて、いろんなプロダクトの試しに使ってみたいのですが、東京に住んでいたら一度お会いして僕のサーバーにデプロイしていただけないでしょうか?
成果報酬などはプライベートなメッセージでやり取りをしましょう

**Comment by genya0407** [comment]
すでにデプロイしているサイトはこちらになります．
https://reing.kuminecraft.xyz/

申し訳ないですが，デプロイに関してはご自分で行ってください．
